### ISSUE TITLE
Clarify Storage Purchase Page

### ISSUE THREAD

**Issue by ellestad** [UCSF-HPC/wynton#16]
Currently states:

All user accounts come with a quota of 500 GiB of storage, which is free of charge

Additional Wynton HPC storage can be purchased at $160/TB (one-time fee)

Please update to something like:

All user accounts come with a quota of 500 GiB of storage in /wynton/home, which is free of charge.

Additional Wynton HPC storage can be purchased in /wynton/group at $160/TB (one-time fee).

Also this line under "Plan"

We are currently offering the ability for research labs to purchase additional storage at a one-time charge of $160/TB for RAID 6 equivalent storage (or $320/TB for mirrored RAID 6)

Change to:

We are currently offering the ability for research labs to purchase additional storage in /wynton/group...

**Comment by HenrikBengtsson** [comment]
<https://wynton.ucsf.edu/hpc/about/pricing-storage.html> updated as:

```diff
diff --git a/docs/about/pricing-storage.md b/docs/about/pricing-storage.md
index 46200ee..d62a760 100644
--- a/docs/about/pricing-storage.md
+++ b/docs/about/pricing-storage.md
@@ -11,9 +11,11 @@ Progress on next storage purchase: <strong>{{ progress }}% ({{ site.data.storage
 
 ## Summary
 
-* All user accounts come with a quota of 500 GiB of storage, which is free of charge
+* All user accounts come with a quota of non-expandable 500 GiB of storage in `/wynton/home`, which is free of char
ge
 
-* Additional {{ site.cluster.name }} storage can be purchased at $160/TB (one-time fee)
+* Global `/wynton/scratch` may be used for smaller, short-term project needs of a few TBs with the caveat that [fil
es older than two weeks are deleted automatically]({{'/about/specs.html#scratch-storage' | relative_url }})
+
+* Additional, long-term storage can be purchased in `/wynton/group` at $160/TB (one-time fee)
 
 * After 5 years from purchase, when the warranty runs out, a small "maintenance fee" might be introduced
```

Does this look ok?

**Comment by ellestad** [comment]
Looks good to me!
