### ISSUE TITLE
Notes on Slurm documentation 

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-HPC/wynton#22]
Proof-reading comments in no particular order:

* https://wynton.ucsf.edu/hpc/slurm/sge-slurm.html
   - [x] SLURM - Slurm
   - [x] pdf -> PDF
   - [x] doc -> document
   - [x] Some code expression use code markup while most don't
   - [x] `#SBATCH --mail-user $USER@ucsf.edu`; is that verbatim `$USER` (does that work?), or is that some pseudo illustration?
   - [x] `#SBATCH --mail-user $USER@ucsf.edu` lacks an equal sign
   - [x] `#SBATCH --mem=4000`; missing unit. I think it's better to train users to always be explicit about the unit, even if there's a default one.
   - [x] One of the examples uses short-form options and the other long-form options, e.g. `#$ -M $USER@ucsf.edu` vs `#SBATCH --mail-user $USER@ucsf.edu`.  Better to stick with one to avoid confusing users, especially beginners.  I suggest using the long format because it clarifies what is specified.  (This comment applies to all Slurm pages)
   - [x] Sometimes 'Title Case', sometimes 'Not title case' in the table, e.g. 'Job Submission' and 'Job deletion'
   - [x] `--exclusive OR--shared`

* https://wynton.ucsf.edu/hpc/slurm/slurm-hello-world-job.html
   - [x] SLURM - Slurm
   - [x] Stray link to Slurm at the bottom of the page

* https://wynton.ucsf.edu/hpc/slurm/submit-jobs.html:
   - [x]  Missing code-markup in several places
   - [x] `JOB_ID` is not a Slurm env var
   - [x] `NSLOTS` is not a Slurm env var
   - [x] Parallel processing (on a single machine): We need an explicit `--nodes=1` in order to avoid ending up on different machines
   - [x] `-n64` is confusing, especially since script example uses `--ntasks=64` but also for new users (see above).  Does it even work? I'd expect either `-n 64` or `--ntasks=64`
 
* https://wynton.ucsf.edu/hpc/slurm/featuresandconstraints.html:
   - [x]  Missing code-markup in several places, which in turn causes double-hyphens to become em-dash
   - [x] --constraint=“cpu_xeon&sse4" -> "cpu_xeon & sse4" (use spacing just like in the next example)
   - [x] "Job requests 32GB of memory (4GB per CPU)" -> "Job requests 32 GiB of memory (4 GiB per CPU)"
   - [x] "10g network connections" -> "10 Gbps network connections"
   - [x] "Select only nodes with sse41 (and above) CPU instruction set" - should use 'SSE4-1'.  Similar for the other entries
   - [x] "Intel Xeon E_52640" -> "Intel Xeon E5-2640"

* https://wynton.ucsf.edu/hpc/slurm/queues.html:
   - [x] `-ntasks=2` - should be double hyphen
   - [x] `--partition <name>` - missing equal sign

* https://wynton.ucsf.edu/hpc/slurm/gpu.html:
   - [x] `-n1`, `-nM`, and `-N1`: use long format

* https://wynton.ucsf.edu/hpc/slurm/email-notifications.html:
   - [x] '–mail-type=ARRAY_TASKS' - missing code markup
   - [x] One example shows `From: root <root@wynton.ucsf.edu>` the other two `From: SLURM <slurm@wynton.ucsf.edu>`

* https://wynton.ucsf.edu/hpc/slurm/advanced-usage.html:
   - [x] To extract the job ID, use argument `--parsable`, cf. https://www.c4.ucsf.edu/scheduler/advanced-usage.html

**Comment by ellestad** [comment]
I have corrected most errors noted.

**Comment by HenrikBengtsson** [comment]
Awesome. Thx.
