### ISSUE TITLE
Current Compute Shares Empty

### ISSUE THREAD

**Issue by ellestad** [UCSF-HPC/wynton#25]
I notice that the Current Compute Shares table is still empty on the Wynton HPC Website.

https://wynton.ucsf.edu/hpc/about/shares.html

Looks like @HenrikBengtsson  is running the cron job that the compute_shares.tsv  is derived from.

The compute_shares.tsv file linked on the website only contains:
```
# Created by: hb
# Created on: 2021-07-13 03:00:03-07:00
# Total fshares: 0
# Total queue_slots: 0
# Number of projects: 1
fshares	queue_slots	project
```

**Comment by HenrikBengtsson** [comment]
Fixed.

**Comment by HenrikBengtsson** [comment]
Hmm... the problem is back.  Something causes this to fail (occasionally?) when running via cronjob.  I'll try to do some more troubleshooting

**Comment by HenrikBengtsson** [comment]
I've updated `make assets` such that it avoid pushing an empty table, cf. commit acc1b85.  I still don't know under what circumstances we end up with an empty table, but I won't dive into that and instead assume that it's temporary and that next update round will get the updated data.
