### ISSUE TITLE
Hide Slurm Pages From Web

### ISSUE THREAD

**Issue by ellestad** [UCSF-HPC/wynton#28]
Slurm pages still show up indexed in google and are available on the web.

Don't want them to show up on web, but also don't want to delete content.

Is there a way to prevent them from being built to html?

Or just create a branch with the Slurm content that can be merged back in?

**Comment by HenrikBengtsson** [comment]
Solved by:

```sh
$ git rm -rf slurm/
```

The page <https://wynton.ucsf.edu/hpc/slurm/submit-jobs.html> that was there before, is now gone.

**Comment by ellestad** [comment]
@HenrikBengtsson The nuclear option, eh. OK, I'll come bother you if we need to recover those pages from previous versions and merge back in if/when we relaunch the Slurm project.

**Comment by HenrikBengtsson** [comment]
I say that's common procedure.

I've tagged the commit prior to the commit where I wiped `docs/slurm/`:

```sh
$ git tag 2021-10-04_with_slurm 46615d940f6bf43f71c7f2982649795afd58a1d3
```

to make it easier to locate in the future:

```sh
$ git tag
0.1.0
2021-10-04_with_slurm
```

and via the GitHub web interface (under '<> Code', click the 'Branch' button and then the 'Tags' tab).
